// MIFFGame - Generated by MIFF ExportPipelinePure
console.log('Game loaded: MIFFGame');
console.log('Engine: web');
console.log('Platform: web_browser');

// Render data
const renderData = [
  {
    "type": "sprite",
    "x": 10,
    "y": 10,
    "width": 32,
    "height": 32,
    "color": "#fff"
  }
];

// Initialize game
function initGame() {
    const canvas = document.getElementById('gameCanvas');
    const ctx = canvas.getContext('2d');
    
    // Basic game loop
    function gameLoop() {
        ctx.fillStyle = '#000';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        
        // Render game objects
        renderData.forEach(item => {
            if (item.type === 'sprite') {
                ctx.fillStyle = item.color || '#fff';
                ctx.fillRect(item.x || 0, item.y || 0, item.width || 32, item.height || 32);
            }
        });
        
        requestAnimationFrame(gameLoop);
    }
    
    gameLoop();
}

// Start game when page loads
window.addEventListener('load', initGame);
