name: link-check

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install lychee
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          args: >-
            --verbose --no-progress --max-concurrency 6
            --include-fragments
            --base .
            ./site/**/*.html ./docs/**/*.md ./docs/site/**/*.html
